language: php

dist: trusty

php:
 - 7.0
 - 7.1
 - hhvm

matrix:
 include:
  - php: 7.1
    env: COVERAGE=yes
 allow_failures:
  - php: hhvm

cache:
 directories:
  - $HOME/.composer/cache

before_script:
 - composer self-update

install:
 - composer install --prefer-source

script:
 - composer test
 - if [[ $COVERAGE == yes ]]; then composer testc; fi
 - if [[ $COVERAGE == yes ]]; then composer check-code; fi

after_success:
 - if [[ $COVERAGE == yes ]]; then composer codeclimate-send-coverage; fi

notifications:
 email: false
