language: php

dist: trusty

php:
 - 5.6
 - 7.0
 - 7.1
 - hhvm

matrix:
 include:
  - php: 7.1
    env: COVERAGE=yes
    env: CHECK_STYLE=yes
 allow_failures:
  - php: hhvm

cache:
 directories:
  - $HOME/.composer/cache

before_script:
 - composer self-update

install:
 - composer install --prefer-source

script:
 - if [[ $CHECK_STYLE == yes ]]; then composer check-code; fi
 - if [[ $COVERAGE == yes ]]; then composer unitc; else composer unit; fi

after_success:
 - if [[ $COVERAGE == yes ]]; then composer codeclimate-send-coverage; fi

notifications:
 email: false
