language: php

php:
 - 5.6
 - 7.0
 - 7.1
 - hhvm

matrix:
 allow_failures:
  - php: 7.1
  - php: hhvm

before_script:
 - composer self-update

install:
 - composer install --prefer-source

script:
 - composer test
 - composer check-code

notifications:
  email: "widmogrod+php-functional@gmail.com"
