language: php

dist: trusty

php:
 - 5.6
 - 7.0
 - 7.1
 - hhvm-3.12

matrix:
 allow_failures:
  - php: hhvm-3.12

before_script:
 - composer self-update

install:
 - composer install --prefer-source

script:
 - composer test
 - composer check-code

notifications:
  email: "widmogrod+php-functional@gmail.com"
